// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBman9ocvxw_3OCCxud2UP22mk_JR-NUD8',
    appId: '1:729334007060:web:8e4b8e07f50cd91ba32e01',
    messagingSenderId: '729334007060',
    projectId: 'oasis-athletics-56294',
    authDomain: 'oasis-athletics-56294.firebaseapp.com',
    storageBucket: 'oasis-athletics-56294.firebasestorage.app',
    measurementId: 'G-F3S378K9EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3RY3_z9ROrOtWzu3UNeoz99heNCpCSk',
    appId: '1:729334007060:android:b94811a0526789c1a32e01',
    messagingSenderId: '729334007060',
    projectId: 'oasis-athletics-56294',
    storageBucket: 'oasis-athletics-56294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdS3IkcZezLE2fQ4yAe5F3SLZGUWaCLn8',
    appId: '1:729334007060:ios:e9536dce7b2db05fa32e01',
    messagingSenderId: '729334007060',
    projectId: 'oasis-athletics-56294',
    storageBucket: 'oasis-athletics-56294.firebasestorage.app',
    iosBundleId: 'com.example.oasisAthleticsn.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdS3IkcZezLE2fQ4yAe5F3SLZGUWaCLn8',
    appId: '1:729334007060:ios:47f89b612a8e0db3a32e01',
    messagingSenderId: '729334007060',
    projectId: 'oasis-athletics-56294',
    storageBucket: 'oasis-athletics-56294.firebasestorage.app',
    iosBundleId: 'com.example.oasisAthleticsn',
  );
}
